language: node_js
node_js:
  - lts/*
script:
  - npm run lint
build:
  - npm run build --production
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_DEPLOY
    keep_history: true
    on:
      branch: master
    path: './build'